```{r}
#import data, empty string as NA, string as factor
data = read.csv("Churn.csv", sep = ";", na.strings = "", stringsAsFactors = T)
head(data)
summary(data)
```
Colums
```{r}
#Organizing colums names
colnames(data) = c("Id", "Score", "Estado", "Genero", "Idade", "Patrimonio","Saldo", 
                   "Produtos", "TemCartCredito", "Ativo", "Salario", "Saiu")
head(data)
```
Exploring categorical data
```{r}
#Estados
counts = table(data$Estado)
barplot(counts, main="Estados", xlab="Estados")

#Gênero
counts = table(data$Genero)
barplot(counts, main = "Gêneros", xlab="Gêneros")
```
Exploring numerical data
```{r}
#Score
summary(data$Score)
boxplot(data$Score)
hist(data$Score)
```
Idade
```{r}
summary(data$Idade)
boxplot(data$Idade)
hist(data$Idade)
```
Saldo
```{r}
summary(data$Saldo)
boxplot(data$Saldo)
hist(data$Saldo)
```
Salário
```{r}
summary(data$Salario)
boxplot(data$Salario)
boxplot(data$Salario, outline = F)
```
Missing Values - NAS
```{r}
#NAS
data[!complete.cases(data),]
```
Salarios
```{r}
#organizing salarios
summary(data$Salario)
#median
median(data$Salario, na.rm = T)
#NAS with median
data[is.na(data$Salario),]$Salario = median(data$Salario, na.rm=T)
#checking NAS in salario
data[!complete.cases(data$Salario),]
```
Missing pattern in Genero
```{r}
#Values
unique(data$Genero)
summary(data$Genero)
# F and Fem -> Feminino/ "", M -> Masculino
data[is.na(data$Genero) | data$Genero == "M",]$Genero = "Masculino"
data[data$Genero == "F" | data $Genero == "Fem",]$Genero = "Feminino"
#Result
summary(data$Genero)
#removing unused levels
data$Genero = factor(data$Genero)
# check
summary(data$Genero)
```
Idade out of domain
```{r}
summary(data$Idade)
#out of domain, numerical = weird idades
data[data$Idade < 0 | data$Idade > 110,]$Idade
#checking NAS
data[is.na(data$Idade),]
#option, filling with median
median(data$Idade)
#substitution
data[data$Idade < 0 | data$Idade > 110 ,]$Idade = median(data$Idade)
#weird idades
data[data$Idade < 0 | data$Idade > 110 ,]
summary(data$Idade)
```
Duplicated Data
```{r}
#searching duplicated data by id
x = data[duplicated(data$Id),]
x
#ID 81 is duplicated
data = data[-c(82),]
#searching duplicated line
data[data$Id == x$Id,]
#checking duplicated data once more
x = data[duplicated(data$Id),]
x
```
Estado out of domain
```{r}
# out of domain - categorical
unique(data$Estado)
summary(data$Estado)
#model, RS
data[!data$Estado %in% c("RS", "SC", "PR"),]$Estado = "RS"
summary(data$Estado)
#deleting non used factors
data$Estado = factor(data$Estado)
#checking
summary(data$Estado)
```
Outliers
```{r}
#outliers, creating a parameter with standard deviation
desv = sd(data$Salario, na.rm = T)
desv
data[data$Salario >= 2 * desv ,]$Salario
#Another way without NAS
boxplot(data$Salario)
boxplot(data$Salario, outline = F)
x = boxplot(data$Salario)$out
x
#updating all to median
median(data$Salario)
data[data$Salario >= 2 * desv ,]$Salario = median(data$Salario)
#checking outliers
data[data$Salario >= 2 * desv , ]$Salario
```

